const quote = [
    { "id": 1, "quote": "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela" },
    { "id": 2, "quote": "The way to get started is to quit talking and begin doing. - Walt Disney" },
    { "id": 3, "quote": "Your time is limited, don't waste it living someone else's life. - Steve Jobs" },
    { "id": 4, "quote": "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt" },
    { "id": 5, "quote": "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey" },
    { "id": 6, "quote": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron" },
    { "id": 7, "quote": "Life is what happens when you're busy making other plans. - John Lennon" },
    { "id": 8, "quote": "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa" },
    { "id": 9, "quote": "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" },
    { "id": 10, "quote": "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead" },
    { "id": 11, "quote": "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson" },
    { "id": 12, "quote": "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" },
    { "id": 13, "quote": "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin" },
    { "id": 14, "quote": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" },
    { "id": 15, "quote": "It is during our darkest moments that we must focus to see the light. - Aristotle" },
    { "id": 16, "quote": "Whoever is happy will make others happy too. - Anne Frank" },
    { "id": 17, "quote": "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson" },
    { "id": 18, "quote": "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou" },
    { "id": 19, "quote": "The only impossible journey is the one you never begin. - Tony Robbins" },
    { "id": 20, "quote": "In this life we cannot do great things. We can only do small things with great love. - Mother Teresa" },
    { "id": 21, "quote": "Only a life lived for others is a life worthwhile. - Albert Einstein" },
    { "id": 22, "quote": "The purpose of our lives is to be happy. - Dalai Lama" },
    { "id": 23, "quote": "Life is what happens when you're busy making other plans. - John Lennon" },
    { "id": 24, "quote": "Get busy living or get busy dying. - Stephen King" },
    { "id": 25, "quote": "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy" },
    { "id": 26, "quote": "Believe you can and you're halfway there. - Theodore Roosevelt" },
    { "id": 27, "quote": "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt" },
    { "id": 28, "quote": "Do what you can, with what you have, where you are. - Theodore Roosevelt" },
    { "id": 29, "quote": "If you can dream it, you can achieve it. - Zig Ziglar" },
    { "id": 30, "quote": "The only way to do great work is to love what you do. - Steve Jobs" },
    { "id": 31, "quote": "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill" },
    { "id": 32, "quote": "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis" },
    { "id": 33, "quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson" },
    { "id": 34, "quote": "The best revenge is massive success. - Frank Sinatra" },
    { "id": 35, "quote": "It does not matter how slowly you go as long as you do not stop. - Confucius" },
    { "id": 36, "quote": "Everything you’ve ever wanted is on the other side of fear. - George Addair" },
    { "id": 37, "quote": "Do one thing every day that scares you. - Eleanor Roosevelt" },
    { "id": 38, "quote": "Dream big and dare to fail. - Norman Vaughan" },
    { "id": 39, "quote": "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi" },
    { "id": 40, "quote": "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King, Jr." },
    { "id": 41, "quote": "Don't watch the clock; do what it does. Keep going. - Sam Levenson" },
    { "id": 42, "quote": "A person who never made a mistake never tried anything new. - Albert Einstein" },
    { "id": 43, "quote": "It's not the years in your life that count. It's the life in your years. - Abraham Lincoln" },
    { "id": 44, "quote": "Life is ten percent what happens to us and ninety percent how we respond to it. - Charles R. Swindoll" },
    { "id": 45, "quote": "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman" },
    { "id": 46, "quote": "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh" },
    { "id": 47, "quote": "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt" },
    { "id": 48, "quote": "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll" },
    { "id": 49, "quote": "Act as if what you do makes a difference. It does. - William James" },
    { "id": 50, "quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson" },
    { "id": 51, "quote": "You cannot change your destination overnight, but you can change your direction overnight. - Jim Rohn" },
    { "id": 52, "quote": "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar" },
    { "id": 53, "quote": "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill" },
    { "id": 54, "quote": "The only place where success comes before work is in the dictionary. - Vidal Sassoon" },
    { "id": 55, "quote": "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson" },
    { "id": 56, "quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit. - Conrad Hilton" },
    { "id": 57, "quote": "If you really look closely, most overnight successes took a long time. - Steve Jobs" },
    { "id": 58, "quote": "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" },
    { "id": 59, "quote": "The only way to do great work is to love what you do. - Steve Jobs" },
    { "id": 60, "quote": "You don't have to be great to start, but you have to start to be great. - Zig Ziglar" },
    { "id": 61, "quote": "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb" },
    { "id": 62, "quote": "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale" },
    { "id": 63, "quote": "It’s not whether you get knocked down. It’s whether you get up. - Vince Lombardi" },
    { "id": 64, "quote": "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn" },
    { "id": 65, "quote": "The people who are crazy enough to think they can change the world, are the ones who do. - Steve Jobs" },
    { "id": 66, "quote": "Don’t watch the clock; do what it does. Keep going. - Sam Levenson" },
    { "id": 67, "quote": "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau" },
    { "id": 68, "quote": "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller" },
    { "id": 69, "quote": "I failed my way to success. - Thomas Edison" },
    { "id": 70, "quote": "Success is not in what you have, but who you are. - Bo Bennett" },
    { "id": 71, "quote": "To be successful, you have to have your heart in your business, and your business in your heart. - Thomas Watson Sr." },
    { "id": 72, "quote": "Success means doing the best we can with what we have. - Zig Ziglar" },
    { "id": 73, "quote": "The only place where success comes before work is in the dictionary. - Vidal Sassoon" },
    { "id": 74, "quote": "You must expect great things of yourself before you can do them. - Michael Jordan" },
    { "id": 75, "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer" },
    { "id": 76, "quote": "The difference between who you are and who you want to be is what you do. - Unknown" },
    { "id": 77, "quote": "The best revenge is massive success. - Frank Sinatra" },
    { "id": 78, "quote": "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson" },
    { "id": 79, "quote": "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau" },
    { "id": 80, "quote": "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn" },
    { "id": 81, "quote": "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett" },
    { "id": 82, "quote": "Try not to become a man of success. Rather become a man of value. - Albert Einstein" },
    { "id": 83, "quote": "Stop chasing the money and start chasing the passion. - Tony Hsieh" },
    { "id": 84, "quote": "Success is not in what you have, but who you are. - Bo Bennett" },
    { "id": 85, "quote": "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou" },
    { "id": 86, "quote": "To be successful, you have to have your heart in your business, and your business in your heart. - Thomas Watson Sr." },
    { "id": 87, "quote": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer" },
    { "id": 88, "quote": "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh" },
    { "id": 89, "quote": "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb" },
    { "id": 90, "quote": "You must expect great things of yourself before you can do them. - Michael Jordan" },
    { "id": 91, "quote": "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller" },
    { "id": 92, "quote": "I failed my way to success. - Thomas Edison" },
    { "id": 93, "quote": "Stop chasing the money and start chasing the passion. - Tony Hsieh" },
    { "id": 94, "quote": "Success means doing the best we can with what we have. - Zig Ziglar" },
    { "id": 95, "quote": "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett" },
    { "id": 96, "quote": "Try not to become a man of success. Rather become a man of value. - Albert Einstein" },
    { "id": 97, "quote": "Stop chasing the money and start chasing the passion. - Tony Hsieh" },
    { "id": 98, "quote": "Success is not in what you have, but who you are. - Bo Bennett" },
    { "id": 99, "quote": "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou" },
    { "id": 100, "quote": "To be successful, you have to have your heart in your business, and your business in your heart. - Thomas Watson Sr." }
]


export default quote